In [5]:
import pandas as pd

# Load the data into 'df' DataFrame
df = pd.read_excel(r"C:\Users\lroes\Documents\DCU\DA Marketing\CA259 Students_first attempt_input.xlsx") 

# Calculate Q1 and Q3
Q1 = df['Age (in years)'].quantile(0.25)
Q3 = df['Age (in years)'].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Define bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = df[(df['Age (in years)'] < lower_bound) | (df['Age (in years)'] > upper_bound)]
print("Outliers in the 'Age (in years)' column:\n", outliers)

Outliers in the 'Age (in years)' column:
      Age (in years)  CAO Points (100 to 600)  \
25               28                      366
29               28                      350
32               36                      243
38               33                      550
60               32                      400
62               26                      545
84               36                      534
87               26                      490
92               33                      380
95               47                      490
103              58                      509

     Daily travel to DCU (in km, 0 if on-campus)  \
25                                          20.0
29                                           8.0
32                                           5.0
38                                           6.7
60                                          10.0
62                                          27.0
84                                          35.0
87                                           3.0
92                                          20.0
95                                           0.0
103                                         59.0

     Average year 1 exam result (as %)  Seat row in class             Gender  \
25                                72.0                  8  Prefer not to say
29                                55.0                 10               Male
32                                72.0                  2             Female
38                                99.0                  8               Male
60                                70.0                  5             Female
62                                68.0                  3             Female
84                                74.0                  8               Male
87                                73.0                  3             Female
92                                86.0                 10               Male
95                                50.0                 12               Male
103                               76.0                 12               Male

     Number of older siblings  Number of younger siblings  \
25                          4                           0
29                          2                           1
32                          2                           0
38                          2                           1
60                          3                           2
62                          2                           1
84                          2                           1
87                          0                           2
92                          2                           1
95                          7                           2
103                         1                           4

     Old Dublin postcode (0 if outside Dublin)  Height (in cm)  ...  \
25                                          18           197.0  ...
29                                           5           170.0  ...
32                                           9           168.0  ...
38                                          12           180.0  ...
60                                           1           170.0  ...
62                                          19           175.0  ...
84                                           5           183.0  ...
87                                           0           169.0  ...
92                                           0           194.0  ...
95                                           3           150.0  ...
103                                          4           190.0  ...

     Hair colour Last 4 digits of your mobile (0000 to 9999)    Star sign  \
25         Brown                                        8798        Aries
29        Blonde                                        7501       Gemini
32           Red                                        8973       Cancer
38         Black                                        2356      Scorpio
60        Blonde                                        9876     Aquarius
62         Brown                                        6798       Gemini
84         Brown                                        8532       Taurus
87         Brown                                        2424       Gemini
92         Brown                                        3675  Sagittarius
95           Red                                        6969        Pices
103        Black                                        7084        Libra

     Shoe size Last 4 digits of your mobile (same as on previous form)  \
25        10.0                                             8798.0
29         9.0                                                NaN
32         8.0                                                NaN
38        10.0                                                NaN
60         9.0                                                NaN
62         7.0                                                NaN
84        10.0                                                NaN
87         8.0                                             2424.0
92         8.0                                                NaN
95         3.0                                                NaN
103       10.0                                             7084.0

     Your rating for EXTRAVERSION (vs. introversion)  \
25                                              22.0
29                                               NaN
32                                               NaN
38                                               NaN
60                                               NaN
62                                               NaN
84                                               NaN
87                                              46.0
92                                               NaN
95                                               NaN
103                                             32.0

     Your rating for INTUITION (vs. observation)  \
25                                          48.0
29                                           NaN
32                                           NaN
38                                           NaN
60                                           NaN
62                                           NaN
84                                           NaN
87                                          43.0
92                                           NaN
95                                           NaN
103                                         45.0

     Your rating for THINKING (vs. feeling)  \
25                                     59.0
29                                      NaN
32                                      NaN
38                                      NaN
60                                      NaN
62                                      NaN
84                                      NaN
87                                     66.0
92                                      NaN
95                                      NaN
103                                    35.0

     Your rating for JUDGING (vs. prospecting)  \
25                                        75.0
29                                         NaN
32                                         NaN
38                                         NaN
60                                         NaN
62                                         NaN
84                                         NaN
87                                        47.0
92                                         NaN
95                                         NaN
103                                       49.0

     Your rating for ASSERTIVE (vs. turbulent)
25                                        56.0
29                                         NaN
32                                         NaN
38                                         NaN
60                                         NaN
62                                         NaN
84                                         NaN
87                                        49.0
92                                         NaN
95                                         NaN
103                                       36.0

[11 rows x 22 columns]